11/02/2023 23:57:13 - WARNING - __main__ - device: cuda:3, n_gpu: 8, 16-bits training: True
Using pad_token, but it is not set yet.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:10<00:20, 10.24s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:20<00:10, 10.08s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:27<00:00,  8.59s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:27<00:00,  9.01s/it]
11/03/2023 00:00:22 - INFO - __main__ - Namespace(model_type='llama', model_name_or_path='meta-llama/Llama-2-13b-chat-hf', prompt='combined_facts.txt', length=300, num_hidden_layers=None, stop_token=None, temperature=1.0, repetition_penalty=1.0, k=0, p=0, prefix='', suffix='', padding_text='', xlm_language='', seed=42, num_anchors=2, num_templates=2, token_count_file='token_counts.json', data_file='combined_facts.txt', data_folder=42, no_cuda=False, stream_output=False, num_return_sequences=1, fp16=True, jit=False, device=device(type='cuda', index=3), n_gpu=8)
Traceback (most recent call last):
  File "/raid/infolab/ashwinr/RoPE/unlimiformer/src/data1_large/run_generation_standard.py", line 590, in <module>
    main()
  File "/raid/infolab/ashwinr/RoPE/unlimiformer/src/data1_large/run_generation_standard.py", line 487, in main
    model = Unlimiformer.convert_model(model, **unlimiformer_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/infolab/ashwinr/RoPE/unlimiformer/src/data1_large/unlimiformer_standard.py", line 958, in convert_model
    type_to_class[type(model)](model, *args, **kwargs)
  File "/raid/infolab/ashwinr/RoPE/unlimiformer/src/data1_large/unlimiformer_standard.py", line 1161, in __init__
    super().__init__(model, *args, **kwargs)
  File "/raid/infolab/ashwinr/RoPE/unlimiformer/src/data1_large/unlimiformer_standard.py", line 51, in __init__
    self.fact_lengths = json.loads(f.read())["fact_lengths"]
                        ^^^^
NameError: name 'json' is not defined
